#include <vector>
using namespace std;
int leetspeakgenerator();
int hoofdletterding();
int testing();
int hollowsquare();
int vierkant();
int driehoek();
int omgekeerdedriehoek();
int piramide();
int omgekeerdepiramide();
int vektor();
int teller(const vector<int> & numbers, const int & x);
float minimum(const vector<float> & cijfers);
int amplitud(const vector<int> & cijfers);
int muggenzifter();
float sprong(const vector<float> & cijfers);
void eennulvoorwaarde(const vector<int> & binair);
vector<float> SumVectoren(const vector<float> & cijfers, const vector<float> & nummers);
int omdraaier();
bool sortcontrole(vector<int> & victor);
void Vectorinput();
int piramide2();